class Constant:

    MAX_STAMINA = 12

    STAMINA_RECOVER_TICK = 1800000

    CORE_EXP = 250

    LEVEL_STEPS = {1: 0, 2: 50, 3: 100, 4: 150, 5: 200, 6: 300, 7: 450, 8: 650, 9: 900, 10: 1200, 11: 1600, 12: 2100, 13: 2700, 14: 3400, 15: 4200, 16: 5100,
                   17: 6100, 18: 7200, 19: 8500, 20: 10000, 21: 11500, 22: 13000, 23: 14500, 24: 16000, 25: 17500, 26: 19000, 27: 20500, 28: 22000, 29: 23500, 30: 25000}

    ETO_UNCAP_BONUS_PROGRESS = 7
    LUNA_UNCAP_BONUS_PROGRESS = 7
    AYU_UNCAP_BONUS_PROGRESS = 5

    story_data = [{
        "ma": 1,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 7,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 8,
        "c": True,
        "r": True
    }, {
        "ma": 1,
        "mi": 9,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 7,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 8,
        "c": True,
        "r": True
    }, {
        "ma": 2,
        "mi": 9,
        "c": True,
        "r": True
    }, {
        "ma": 100,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 100,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 100,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 100,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 100,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 7,
        "c": True,
        "r": True
    }, {
        "ma": 101,
        "mi": 8,
        "c": True,
        "r": True
    }, {
        "ma": 3,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 3,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 3,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 3,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 3,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 3,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 7,
        "c": True,
        "r": True
    }, {
        "ma": 4,
        "mi": 8,
        "c": True,
        "r": True
    }, {
        "ma": 99,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 99,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 99,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 99,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 99,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 99,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 5,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 5,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 5,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 5,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 5,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 5,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 7,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 7,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 7,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 7,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 7,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 7,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 9,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 9,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 9,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 9,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 9,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 9,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 10,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 10,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 10,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 10,
        "mi": 4,
        "c": True,
        "r": True
    }, {
        "ma": 10,
        "mi": 5,
        "c": True,
        "r": True
    }, {
        "ma": 10,
        "mi": 6,
        "c": True,
        "r": True
    }, {
        "ma": 6,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 6,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 6,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 8,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 8,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 8,
        "mi": 3,
        "c": True,
        "r": True
    }, {
        "ma": 11,
        "mi": 1,
        "c": True,
        "r": True
    }, {
        "ma": 11,
        "mi": 2,
        "c": True,
        "r": True
    }, {
        "ma": 11,
        "mi": 3,
        "c": True,
        "r": True
    }]
    unlocklist_data = [{
        "unlock_key": "worldvanquisher|1|0",
        "complete": 1
    }, {
        "unlock_key": "worldexecuteme|2|0",
        "complete": 1
    }, {
        "unlock_key": "vector|1|0",
        "complete": 1
    }, {
        "unlock_key": "valhallazero|1|0",
        "complete": 1
    }, {
        "unlock_key": "tiferet|2|0",
        "complete": 1
    }, {
        "unlock_key": "tiferet|1|0",
        "complete": 1
    }, {
        "unlock_key": "tiemedowngently|2|0",
        "complete": 1
    }, {
        "unlock_key": "tempestissimo|2|101",
        "complete": 100
    }, {
        "unlock_key": "tempestissimo|1|101",
        "complete": 100
    }, {
        "unlock_key": "syro|2|0",
        "complete": 1
    }, {
        "unlock_key": "syro|1|0",
        "complete": 1
    }, {
        "unlock_key": "supernova|2|0",
        "complete": 1
    }, {
        "unlock_key": "solitarydream|2|0",
        "complete": 1
    }, {
        "unlock_key": "snowwhite|2|0",
        "complete": 1
    }, {
        "unlock_key": "senkyou|1|0",
        "complete": 1
    }, {
        "unlock_key": "senkyou|2|0",
        "complete": 1
    }, {
        "unlock_key": "seclusion|1|0",
        "complete": 1
    }, {
        "unlock_key": "scarletlance|2|0",
        "complete": 1
    }, {
        "unlock_key": "toaliceliddell|1|0",
        "complete": 1
    }, {
        "unlock_key": "scarletlance|1|0",
        "complete": 1
    }, {
        "unlock_key": "aterlbus|1|0",
        "complete": 1
    }, {
        "unlock_key": "rugie|2|0",
        "complete": 1
    }, {
        "unlock_key": "rise|2|0",
        "complete": 1
    }, {
        "unlock_key": "revixy|2|0",
        "complete": 1
    }, {
        "unlock_key": "reinvent|2|0",
        "complete": 1
    }, {
        "unlock_key": "felis|1|0",
        "complete": 1
    }, {
        "unlock_key": "rekkaresonance|2|0",
        "complete": 1
    }, {
        "unlock_key": "reinvent|1|0",
        "complete": 1
    }, {
        "unlock_key": "essenceoftwilight|1|0",
        "complete": 1
    }, {
        "unlock_key": "redandblue|2|0",
        "complete": 1
    }, {
        "unlock_key": "espebranch|1|0",
        "complete": 1
    }, {
        "unlock_key": "redandblue|1|0",
        "complete": 1
    }, {
        "unlock_key": "supernova|1|0",
        "complete": 1
    }, {
        "unlock_key": "lostcivilization|2|0",
        "complete": 1
    }, {
        "unlock_key": "rabbitintheblackroom|2|0",
        "complete": 1
    }, {
        "unlock_key": "pragmatism|1|0",
        "complete": 1
    }, {
        "unlock_key": "rabbitintheblackroom|1|0",
        "complete": 1
    }, {
        "unlock_key": "suomi|1|0",
        "complete": 1
    }, {
        "unlock_key": "ringedgenesis|2|0",
        "complete": 1
    }, {
        "unlock_key": "quon|1|0",
        "complete": 1
    }, {
        "unlock_key": "qualia|2|0",
        "complete": 1
    }, {
        "unlock_key": "purgatorium|2|0",
        "complete": 1
    }, {
        "unlock_key": "halcyon|2|0",
        "complete": 1
    }, {
        "unlock_key": "saikyostronger|2|3|einherjar|2",
        "complete": 6
    }, {
        "unlock_key": "cyanine|2|0",
        "complete": 1
    }, {
        "unlock_key": "saikyostronger|2|3|laqryma|2",
        "complete": 1
    }, {
        "unlock_key": "purgatorium|1|0",
        "complete": 1
    }, {
        "unlock_key": "tiemedowngently|1|0",
        "complete": 1
    }, {
        "unlock_key": "ouroboros|2|0",
        "complete": 1
    }, {
        "unlock_key": "ringedgenesis|1|0",
        "complete": 1
    }, {
        "unlock_key": "ouroboros|1|0",
        "complete": 1
    }, {
        "unlock_key": "partyvinyl|2|0",
        "complete": 1
    }, {
        "unlock_key": "oracle|1|0",
        "complete": 1
    }, {
        "unlock_key": "onelastdrive|2|0",
        "complete": 1
    }, {
        "unlock_key": "nirvluce|1|0",
        "complete": 1
    }, {
        "unlock_key": "onelastdrive|1|0",
        "complete": 1
    }, {
        "unlock_key": "omegafour|1|0",
        "complete": 1
    }, {
        "unlock_key": "harutopia|1|0",
        "complete": 1
    }, {
        "unlock_key": "anokumene|1|0",
        "complete": 1
    }, {
        "unlock_key": "oblivia|2|0",
        "complete": 1
    }, {
        "unlock_key": "nhelv|2|0",
        "complete": 1
    }, {
        "unlock_key": "memoryforest|1|0",
        "complete": 1
    }, {
        "unlock_key": "melodyoflove|2|0",
        "complete": 1
    }, {
        "unlock_key": "omegafour|2|0",
        "complete": 1
    }, {
        "unlock_key": "melodyoflove|1|0",
        "complete": 1
    }, {
        "unlock_key": "medusa|1|0",
        "complete": 1
    }, {
        "unlock_key": "mazymetroplex|2|0",
        "complete": 1
    }, {
        "unlock_key": "seclusion|2|0",
        "complete": 1
    }, {
        "unlock_key": "lucifer|2|0",
        "complete": 1
    }, {
        "unlock_key": "gloryroad|1|0",
        "complete": 1
    }, {
        "unlock_key": "babaroque|2|0",
        "complete": 1
    }, {
        "unlock_key": "lucifer|1|0",
        "complete": 1
    }, {
        "unlock_key": "lostdesire|2|0",
        "complete": 1
    }, {
        "unlock_key": "solitarydream|1|0",
        "complete": 1
    }, {
        "unlock_key": "lostdesire|1|0",
        "complete": 1
    }, {
        "unlock_key": "lostcivilization|1|0",
        "complete": 1
    }, {
        "unlock_key": "loschen|1|0",
        "complete": 1
    }, {
        "unlock_key": "aegleseeker|2|3|paperwitch|2",
        "complete": 10
    }, {
        "unlock_key": "livefastdieyoung|1|0",
        "complete": 1
    }, {
        "unlock_key": "shadesoflight|1|0",
        "complete": 1
    }, {
        "unlock_key": "kanagawa|2|0",
        "complete": 1
    }, {
        "unlock_key": "ifi|2|0",
        "complete": 1
    }, {
        "unlock_key": "kanagawa|1|0",
        "complete": 1
    }, {
        "unlock_key": "jump|1|0",
        "complete": 1
    }, {
        "unlock_key": "grievouslady|1|101",
        "complete": 100
    }, {
        "unlock_key": "infinityheaven|1|0",
        "complete": 1
    }, {
        "unlock_key": "worldvanquisher|2|0",
        "complete": 1
    }, {
        "unlock_key": "bookmaker|2|0",
        "complete": 1
    }, {
        "unlock_key": "ignotus|2|0",
        "complete": 1
    }, {
        "unlock_key": "ignotus|1|0",
        "complete": 1
    }, {
        "unlock_key": "sheriruth|2|0",
        "complete": 1
    }, {
        "unlock_key": "medusa|2|0",
        "complete": 1
    }, {
        "unlock_key": "heavensdoor|2|0",
        "complete": 1
    }, {
        "unlock_key": "nhelv|1|0",
        "complete": 1
    }, {
        "unlock_key": "harutopia|2|0",
        "complete": 1
    }, {
        "unlock_key": "guardina|2|0",
        "complete": 1
    }, {
        "unlock_key": "lethaeus|1|0",
        "complete": 1
    }, {
        "unlock_key": "saikyostronger|2|0",
        "complete": 1
    }, {
        "unlock_key": "guardina|0|0",
        "complete": 1
    }, {
        "unlock_key": "oshamascramble|2|0",
        "complete": 1
    }, {
        "unlock_key": "aiueoon|2|0",
        "complete": 1
    }, {
        "unlock_key": "blaster|2|0",
        "complete": 1
    }, {
        "unlock_key": "grievouslady|2|101",
        "complete": 100
    }, {
        "unlock_key": "darakunosono|1|0",
        "complete": 1
    }, {
        "unlock_key": "grimheart|1|0",
        "complete": 1
    }, {
        "unlock_key": "ifi|1|0",
        "complete": 1
    }, {
        "unlock_key": "gothiveofra|1|0",
        "complete": 1
    }, {
        "unlock_key": "etherstrike|1|0",
        "complete": 1
    }, {
        "unlock_key": "singularity|2|0",
        "complete": 1
    }, {
        "unlock_key": "lightningscrew|1|0",
        "complete": 1
    }, {
        "unlock_key": "viciousheroism|1|0",
        "complete": 1
    }, {
        "unlock_key": "axiumcrisis|1|0",
        "complete": 1
    }, {
        "unlock_key": "gloryroad|0|0",
        "complete": 1
    }, {
        "unlock_key": "guardina|1|0",
        "complete": 1
    }, {
        "unlock_key": "pragmatism|2|0",
        "complete": 1
    }, {
        "unlock_key": "oracle|2|0",
        "complete": 1
    }, {
        "unlock_key": "genocider|2|0",
        "complete": 1
    }, {
        "unlock_key": "buchigireberserker|2|3|gothiveofra|2",
        "complete": 1
    }, {
        "unlock_key": "genesis|1|0",
        "complete": 1
    }, {
        "unlock_key": "fractureray|1|101",
        "complete": 100
    }, {
        "unlock_key": "freefall|2|0",
        "complete": 1
    }, {
        "unlock_key": "revixy|1|0",
        "complete": 1
    }, {
        "unlock_key": "fractureray|2|101",
        "complete": 100
    }, {
        "unlock_key": "goodtek|1|0",
        "complete": 1
    }, {
        "unlock_key": "monochromeprincess|2|0",
        "complete": 1
    }, {
        "unlock_key": "babaroque|1|0",
        "complete": 1
    }, {
        "unlock_key": "flyburg|2|0",
        "complete": 1
    }, {
        "unlock_key": "clotho|2|0",
        "complete": 1
    }, {
        "unlock_key": "quon|2|0",
        "complete": 1
    }, {
        "unlock_key": "gou|2|0",
        "complete": 1
    }, {
        "unlock_key": "felis|2|0",
        "complete": 1
    }, {
        "unlock_key": "cyaegha|2|0",
        "complete": 1
    }, {
        "unlock_key": "qualia|1|0",
        "complete": 1
    }, {
        "unlock_key": "buchigireberserker|2|0",
        "complete": 1
    }, {
        "unlock_key": "etherstrike|2|0",
        "complete": 1
    }, {
        "unlock_key": "flyburg|1|0",
        "complete": 1
    }, {
        "unlock_key": "shadesoflight|2|0",
        "complete": 1
    }, {
        "unlock_key": "espebranch|2|0",
        "complete": 1
    }, {
        "unlock_key": "anokumene|2|0",
        "complete": 1
    }, {
        "unlock_key": "equilibrium_challenge|2|102",
        "complete": 1
    }, {
        "unlock_key": "overwhelm|2|0",
        "complete": 1
    }, {
        "unlock_key": "chronostasis|2|0",
        "complete": 1
    }, {
        "unlock_key": "gloryroad|2|0",
        "complete": 1
    }, {
        "unlock_key": "neokosmo|1|0",
        "complete": 1
    }, {
        "unlock_key": "akinokagerou|1|0",
        "complete": 1
    }, {
        "unlock_key": "equilibrium_challenge|1|102",
        "complete": 1
    }, {
        "unlock_key": "aterlbus|2|0",
        "complete": 1
    }, {
        "unlock_key": "dreaminattraction|2|0",
        "complete": 1
    }, {
        "unlock_key": "neokosmo|2|0",
        "complete": 1
    }, {
        "unlock_key": "dreaminattraction|1|0",
        "complete": 1
    }, {
        "unlock_key": "divinelight|2|0",
        "complete": 1
    }, {
        "unlock_key": "freefall|1|0",
        "complete": 1
    }, {
        "unlock_key": "darakunosono|2|0",
        "complete": 1
    }, {
        "unlock_key": "goodtek|2|0",
        "complete": 1
    }, {
        "unlock_key": "infinityheaven|2|0",
        "complete": 1
    }, {
        "unlock_key": "dandelion|2|0",
        "complete": 1
    }, {
        "unlock_key": "dandelion|1|0",
        "complete": 1
    }, {
        "unlock_key": "blrink|1|0",
        "complete": 1
    }, {
        "unlock_key": "livefastdieyoung|2|0",
        "complete": 1
    }, {
        "unlock_key": "corpssansorganes|0|0",
        "complete": 1
    }, {
        "unlock_key": "conflict|2|0",
        "complete": 1
    }, {
        "unlock_key": "monochromeprincess|1|0",
        "complete": 1
    }, {
        "unlock_key": "clotho|1|0",
        "complete": 1
    }, {
        "unlock_key": "heavensdoor|1|0",
        "complete": 1
    }, {
        "unlock_key": "chronostasis|1|0",
        "complete": 1
    }, {
        "unlock_key": "lethaeus|2|0",
        "complete": 1
    }, {
        "unlock_key": "amazingmightyyyy|1|0",
        "complete": 1
    }, {
        "unlock_key": "aegleseeker|0|103",
        "complete": 1
    }, {
        "unlock_key": "buchigireberserker|2|3|ouroboros|2",
        "complete": 1
    }, {
        "unlock_key": "oshamascramble|1|0",
        "complete": 1
    }, {
        "unlock_key": "gothiveofra|2|0",
        "complete": 1
    }, {
        "unlock_key": "linearaccelerator|2|0",
        "complete": 1
    }, {
        "unlock_key": "corpssansorganes|1|0",
        "complete": 1
    }, {
        "unlock_key": "viciousheroism|2|0",
        "complete": 1
    }, {
        "unlock_key": "lightningscrew|2|0",
        "complete": 1
    }, {
        "unlock_key": "worldexecuteme|1|0",
        "complete": 1
    }, {
        "unlock_key": "bookmaker|1|0",
        "complete": 1
    }, {
        "unlock_key": "toaliceliddell|2|0",
        "complete": 1
    }, {
        "unlock_key": "overwhelm|1|0",
        "complete": 1
    }, {
        "unlock_key": "nirvluce|2|0",
        "complete": 1
    }, {
        "unlock_key": "genocider|1|0",
        "complete": 1
    }, {
        "unlock_key": "rise|1|0",
        "complete": 1
    }, {
        "unlock_key": "tempestissimo|0|101",
        "complete": 100
    }, {
        "unlock_key": "aegleseeker|2|3|crystalgravity|2",
        "complete": 10
    }, {
        "unlock_key": "tempestissimo|3|101",
        "complete": 100
    }, {
        "unlock_key": "cyanine|1|0",
        "complete": 1
    }, {
        "unlock_key": "axiumcrisis|2|0",
        "complete": 1
    }, {
        "unlock_key": "suomi|2|0",
        "complete": 1
    }, {
        "unlock_key": "blrink|2|0",
        "complete": 1
    }, {
        "unlock_key": "fractureray|0|101",
        "complete": 100
    }, {
        "unlock_key": "singularity|1|0",
        "complete": 1
    }, {
        "unlock_key": "blaster|1|0",
        "complete": 1
    }, {
        "unlock_key": "aegleseeker|1|103",
        "complete": 1
    }, {
        "unlock_key": "amazingmightyyyy|2|0",
        "complete": 1
    }, {
        "unlock_key": "cyaegha|1|0",
        "complete": 1
    }, {
        "unlock_key": "linearaccelerator|1|0",
        "complete": 1
    }, {
        "unlock_key": "valhallazero|2|0",
        "complete": 1
    }, {
        "unlock_key": "corpssansorganes|2|0",
        "complete": 1
    }, {
        "unlock_key": "conflict|1|0",
        "complete": 1
    }, {
        "unlock_key": "oblivia|1|0",
        "complete": 1
    }, {
        "unlock_key": "cyberneciacatharsis|1|0",
        "complete": 1
    }, {
        "unlock_key": "aegleseeker_challenge|0|102",
        "complete": 1
    }, {
        "unlock_key": "mazymetroplex|1|0",
        "complete": 1
    }, {
        "unlock_key": "viyellastears|2|0",
        "complete": 1
    }, {
        "unlock_key": "equilibrium_challenge|0|102",
        "complete": 1
    }, {
        "unlock_key": "grievouslady|0|101",
        "complete": 100
    }, {
        "unlock_key": "snowwhite|1|0",
        "complete": 1
    }, {
        "unlock_key": "partyvinyl|1|0",
        "complete": 1
    }, {
        "unlock_key": "jump|2|0",
        "complete": 1
    }, {
        "unlock_key": "viyellastears|1|0",
        "complete": 1
    }, {
        "unlock_key": "aegleseeker|2|103",
        "complete": 1
    }, {
        "unlock_key": "grimheart|2|0",
        "complete": 1
    }, {
        "unlock_key": "aegleseeker|2|3|farawaylight|2",
        "complete": 10
    }, {
        "unlock_key": "rugie|1|0",
        "complete": 1
    }, {
        "unlock_key": "gou|1|0",
        "complete": 1
    }, {
        "unlock_key": "sheriruth|1|0",
        "complete": 1
    }, {
        "unlock_key": "aegleseeker|2|3|loschen|2",
        "complete": 10
    }, {
        "unlock_key": "akinokagerou|2|0",
        "complete": 1
    }, {
        "unlock_key": "saikyostronger|2|3|izana|2",
        "complete": 1
    }, {
        "unlock_key": "memoryforest|2|0",
        "complete": 1
    }, {
        "unlock_key": "halcyon|1|0",
        "complete": 1
    }, {
        "unlock_key": "genesis|2|0",
        "complete": 1
    }, {
        "unlock_key": "vector|2|0",
        "complete": 1
    }, {
        "unlock_key": "loschen|2|0",
        "complete": 1
    }, {
        "unlock_key": "divinelight|1|0",
        "complete": 1
    }, {
        "unlock_key": "essenceoftwilight|2|0",
        "complete": 1
    }, {
        "unlock_key": "cyberneciacatharsis|2|0",
        "complete": 1
    }]
